disabled_rules:
  - todo
  - type_body_length
  - file_length
  - nesting # should be re-enabled

opt_in_rules: # some rules are only opt-in
  - explicit_type_interface
  - force_unwrapping
  - implicit_return
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_string
  - contains_over_first_not_nil
  - indentation_width

excluded:
  - Carthage
  - Pods
  - Demos/VaporDemo
  - Demos/PerfectDemo
  - Tests
  - .build

force_cast: warning
force_try: warning

# - Force explicity type for every variable on the project, this is needed to let the Swift compiler more lightweight
explicit_type_interface:
  severity: warning

line_length: 200

indentation_width:
  indentation_width: 2
  include_comments: false
