name: Publish to CocoaPod

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish to CocoaPod
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check release validity
        run: sh .github/scripts/check-release.sh
      - name: Publish to CocoaPod register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push  MeiliSearch.podspec
