name: Tests

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - main

jobs:
  integeration_tests:
    name: integration-tests
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest version of MeiliSearch
        run: |
          curl -u "meili-bot" -s 'https://api.github.com/repos/meilisearch/MeiliSearch/releases' > temp_file
      - name: Grep latest version of MeiliSearch
        run: |
          ls
          cat temp_file
      # echo "MEILISEARCH_RELEASES=$(curl -s 'https://api.github.com/repos/meilisearch/MeiliSearch/releases')" >> $GITHUB_ENV
      # cat ${{ env.MEILISEARCH_RELEASES }} \
      # | grep -E 'tag_name' | grep 'v0' | head -1 \
      # | tr -d ',"' | cut -d ':' -f2 | tr -d ' '
      # - name: Download MeiliSearch
      #   run: |
      #     curl https://github.com/meilisearch/MeiliSearch/releases/download/v0.21.0/meilisearch-macos-amd64 --output meilisearch --location
      #     chmod +x meilisearch
      # - name: Run MeiliSearch
      #   run: |
      #     ./meilisearch --master-key=masterKey --no-analytics true &
      # - name: Run tests
      #   run: swift test

  linter:
    name: linter-check
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run SwiftLint
        run: sh ./Scripts/swiftlint.sh
